apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-example
spec:
  entrypoint: ejemplo       #Pipeline de entrada
  arguments:                #Valores editables que se pueden sobreescribir al implementarlo en un Workflow
    parameters:
      - name: mensaje
        value: hola
  templates:                #Lógica de pipeline que se puede consumir en un Workflow
    - name: ejemplo
      inputs:               #Relaciona el 'arguments' como variable de entrada
        parameters:
          - name: mensaje
      container:  
        image: busybox
        command: [sh, -c]
        args:
        - "export mensaje={{inputs.parameters.mensaje}}"
        - "echo $mensaje > /tmp/entrada.txt"
        - "echo -n hello world > /tmp/hello_world.txt"
      outputs:            #Variables de salida
        parameters:       #Salida de parámetros/metadata
        - name: contenido-hello-world 
          valueFrom:
            path: /tmp/hello_world.txt
        artifacts:        #Salida de objetos (carpetas, archivos, etc)
        - name: archivos
          path: /tmp




